#!/usr/bin/env node
/**
 * Submit URLs to Bing via the IndexNow protocol.
 *
 * Why this exists: a new landing page can take days to appear in Bing's index
 * through normal crawling. ChatGPT's search leans heavily on Bing's index, so
 * that delay is a GEO delay, not just an SEO one. IndexNow pushes a URL to
 * Bing, Yandex and the other participating engines the moment it is deployed,
 * which typically brings it live in about an hour.
 *
 * Setup, once:
 *
 *   1. Bing Webmaster Tools -> your site -> IndexNow -> create key
 *      (a lowercase alphanumeric string)
 *   2. Host that key at the site root, e.g. public/<key>.txt containing the key
 *   3. Set INDEXNOW_KEY and run this script after each deploy
 *
 * The key file must be published for verification to succeed; IndexNow returns
 * 200 only if it can fetch the key from the URL, so a key that is set but not
 * hosted will report success-looking 202s and change nothing.
 *
 * Usage:
 *   INDEXNOW_KEY=abc123 npm run indexnow
 *   INDEXNOW_KEY=abc123 npm run indexnow -- /new-page /blog/new-post
 *   INDEXNOW_KEY=abc123 npm run indexnow -- --all
 */

import { readFile, readdir } from "node:fs/promises";
import { existsSync } from "node:fs";
import { dirname, join, resolve } from "node:path";
import { fileURLToPath } from "node:url";

const ROOT = resolve(dirname(fileURLToPath(import.meta.url)), "..");
const PUBLIC = join(ROOT, "public");
const ORIGIN = "https://worm.clepsydratechnologies.com";
const ENDPOINT = "https://api.indexnow.org/indexnow";

const key = process.env.INDEXNOW_KEY;

if (!key) {
  console.error(
    "INDEXNOW_KEY is not set.\n" +
      "Create a key in Bing Webmaster Tools, host it at the site root, then:\n" +
      "  INDEXNOW_KEY=<key> npm run indexnow -- --all",
  );
  process.exit(1);
}

if (!/^[a-z0-9]{8,128}$/.test(key)) {
  console.error(
    `INDEXNOW_KEY looks malformed: ${JSON.stringify(key)}\n` +
      "It must be 8-128 characters of lowercase letters and digits only.",
  );
  process.exit(1);
}

/* ── Collect URLs ──────────────────────────────────────────────────────── */

async function generatedHrefs(dir, out = []) {
  for (const entry of await readdir(dir, { withFileTypes: true })) {
    const p = join(dir, entry.name);
    if (entry.isDirectory()) {
      if (entry.name === "images") continue;
      await generatedHrefs(p, out);
    } else if (entry.name.endsWith(".html")) {
      // Only submit generated pages. 404.html and the Search Console
      // verification file are hand-authored and must never be sent.
      const contents = await readFile(p, "utf8").catch(() => "");
      if (!contents.includes("Generated by scripts/build-seo-pages.mjs")) continue;
      const rel = p.slice(PUBLIC.length + 1).replace(/\.html$/, "").replace(/\\/g, "/");
      out.push("/" + rel);
    }
  }
  return out;
}

const argv = process.argv.slice(2);

let paths;
if (argv.includes("--all")) {
  paths = ["/", ...(await generatedHrefs(PUBLIC))];
} else if (argv.length) {
  paths = argv.filter((a) => !a.startsWith("--")).map((p) => (p.startsWith("/") ? p : "/" + p));
} else {
  // Default: everything the site publishes. New pages are the whole point of
  // IndexNow, so submitting the full set is cheap and idempotent.
  paths = ["/", ...(await generatedHrefs(PUBLIC))];
}

const urls = paths.map((p) => ORIGIN + (p === "/" ? "/" : p.replace(/\/$/, "")));

/* ── Sanity-check the key file is actually hosted ───────────────────────── */

const keyFile = join(PUBLIC, `${key}.txt`);
if (!existsSync(keyFile)) {
  console.warn(
    `Note: ${key}.txt is not in public/, so the key cannot be verified from the site root.\n` +
      "      IndexNow will still accept the request but the engines will ignore it.\n" +
      `      Add public/${key}.txt containing exactly: ${key}\n`,
  );
}

/* ── Submit ────────────────────────────────────────────────────────────── */

console.log(`Submitting ${urls.length} URL(s) to IndexNow...`);

try {
  const res = await fetch(ENDPOINT, {
    method: "POST",
    headers: { "Content-Type": "application/json; charset=utf-8" },
    body: JSON.stringify({
      host: "worm.clepsydratechnologies.com",
      key,
      keyLocation: `${ORIGIN}/${key}.txt`,
      urlList: urls,
    }),
  });

  const body = (await res.text()).slice(0, 400);

  if (res.ok) {
    console.log(`Accepted (HTTP ${res.status}).${body ? ` ${body}` : ""}`);
    console.log("Bing and other participating engines should re-crawl these within about an hour.");
  } else if (res.status === 422) {
    console.error("Rejected (HTTP 422): the key does not match the key hosted at keyLocation.");
    console.error(`  keyLocation: ${ORIGIN}/${key}.txt`);
    console.error(`  expected contents: ${key}`);
    process.exit(1);
  } else {
    console.error(`Failed (HTTP ${res.status}). ${body}`);
    process.exit(1);
  }
} catch (err) {
  console.error(`Request failed: ${err.message}`);
  process.exit(1);
}