#!/usr/bin/env node
/**
 * Cross-page SEO and GEO consistency checks.
 *
 * The pages in public/ are generated, so they are internally consistent by
 * construction. What is *not* covered by generation is agreement with the rest
 * of the site: the React app's version string, the hand-written index.html,
 * sitemap.xml, llms.txt, and the JSON-LD SoftwareApplication block.
 *
 * That is the failure mode worth guarding. Answer engines compare a source
 * against other sources, and a site that states three different version numbers
 * or two different platform requirements is a site they discount. So this
 * checks the things that are easy to forget and expensive to get wrong:
 *
 *   - every page's JSON-LD parses and carries the required node types
 *   - each FAQPage entry count matches its visible accordion
 *   - exactly one h1 per page, and a description inside the SERP pixel budget
 *   - every internal link resolves, and no page is an orphan
 *   - the version number, platform line and price agree everywhere
 *   - sitemap.xml and llms.txt list every page that exists
 *
 * Exits non-zero on any failure, so it can gate a deploy.
 */

import { readFile, readdir } from "node:fs/promises";
import { existsSync } from "node:fs";
import { dirname, join, resolve } from "node:path";
import { fileURLToPath } from "node:url";

const ROOT = resolve(dirname(fileURLToPath(import.meta.url)), "..");
const PUBLIC = join(ROOT, "public");

const SITE_ORIGIN = "https://worm.clepsydratechnologies.com";

/** Must stay byte-identical to the marker in scripts/seo/render.mjs. */
const GENERATED_MARKER = "Generated by scripts/build-seo-pages.mjs";

const errors = [];
const warnings = [];
const fail = (m) => errors.push(m);
const warn = (m) => warnings.push(m);

/* ── Collect generated pages ───────────────────────────────────────────── */

async function findHtmlFiles(dir, out = []) {
  for (const entry of await readdir(dir, { withFileTypes: true })) {
    const p = join(dir, entry.name);
    if (entry.isDirectory()) {
      if (entry.name === "images") continue;
      await findHtmlFiles(p, out);
    } else if (entry.name.endsWith(".html")) {
      out.push(p);
    }
  }
  return out;
}

// index.html at the site root is the React SPA entry, not a generated page.
// Everything else under public/ was produced by scripts/build-seo-pages.mjs.
// A "generated page" is defined by the ownership stamp, not by its extension.
// public/ also holds hand-authored .html files that must never be validated as
// pages or listed in the sitemap — 404.html and the Google Search Console
// verification file, the latter of which must stay byte-identical forever.
const htmlFiles = await findHtmlFiles(PUBLIC);
const files = [];
for (const f of htmlFiles) {
  const contents = await readFile(f, "utf8").catch(() => "");
  if (contents.includes(GENERATED_MARKER)) files.push(f);
}

const skipped = htmlFiles.length - files.length;
if (skipped > 0) {
  console.log(`Skipped ${skipped} hand-authored .html file(s) in public/.`);
}

const pages = [];
for (const file of files) {
  const html = await readFile(file, "utf8");

  const href = "/" + file.slice(PUBLIC.length + 1).replace(/\.html$/, "").replace(/\\/g, "/");

  const title = html.match(/<title>([\s\S]*?)<\/title>/)?.[1];
  const description = html.match(/<meta name="description" content="([^"]*)"/)?.[1];
  const canonical = html.match(/<link rel="canonical" href="([^"]*)"/)?.[1];

  let graph = null;
  const ldBlock = html.match(/<script type="application\/ld\+json">([\s\S]*?)<\/script>/);
  if (ldBlock) {
    try {
      graph = JSON.parse(ldBlock[1]);
    } catch (e) {
      fail(`${href}: JSON-LD does not parse — ${e.message}`);
    }
  } else {
    fail(`${href}: no JSON-LD block`);
  }

  pages.push({ href, file, html, title, description, canonical, graph });
}

/* ── Per-page checks ───────────────────────────────────────────────────── */

const REQUIRED_TYPES = ["WebPage", "BreadcrumbList", "SoftwareApplication", "FAQPage"];

/**
 * Catch CSS mistakes that are invisible in a diff and easy to ship.
 *
 * An undefined custom property does not throw — `color: var(--typo)` is simply
 * dropped by the parser, so the rule silently loses one declaration and the
 * page still renders. That is exactly the kind of defect that reaches
 * production unnoticed, and it was caught here once already.
 */
function checkStylesheet(p) {
  const styleBlocks = [...p.html.matchAll(/<style>([\s\S]*?)<\/style>/g)].map((m) => m[1]);
  if (styleBlocks.length === 0) return;

  const css = styleBlocks.join("\n");

  let depth = 0;
  for (const ch of css) {
    if (ch === "{") depth++;
    else if (ch === "}") depth--;
    if (depth < 0) break;
  }
  if (depth !== 0) fail(`${p.href}: <style> block has unbalanced braces (${depth} unclosed)`);

  const defined = new Set(
    [...css.matchAll(/(--[a-z0-9-]+)\s*:/g)].map((m) => m[1]),
  );
  const referenced = new Set([...css.matchAll(/var\(\s*(--[a-z0-9-]+)/g)].map((m) => m[1]));

  for (const ref of referenced) {
    if (!defined.has(ref)) {
      fail(`${p.href}: CSS references undefined custom property ${ref} — the declaration using it is silently dropped`);
    }
  }
}

for (const p of pages) {
  if (!p.title) {
    fail(`${p.href}: no <title>`);
  } else if (p.title.length > 62) {
    fail(`${p.href}: title is ${p.title.length} chars (over the ~60 char SERP budget)`);
  }

  if (!p.description) {
    fail(`${p.href}: no meta description`);
  } else if (p.description.length > 165) {
    fail(`${p.href}: meta description is ${p.description.length} chars`);
  }

  const expectedCanonical = p.href === "/" ? `${SITE_ORIGIN}/` : `${SITE_ORIGIN}${p.href}`;
  if (p.canonical !== expectedCanonical) {
    fail(`${p.href}: canonical is "${p.canonical}", expected "${expectedCanonical}"`);
  }

  const h1Count = (p.html.match(/<h1[\s>]/g) || []).length;
  if (h1Count !== 1) fail(`${p.href}: has ${h1Count} <h1> elements, expected exactly 1`);

  checkStylesheet(p);

  // A definition paragraph is what answer engines quote. Its absence is the
  // single most common reason a page gets skipped rather than cited.
  if (!/class="lede"/.test(p.html)) {
    fail(`${p.href}: no .lede definition paragraph in the first screenful`);
  }

  if (p.graph) {
    const types = p.graph["@graph"].map((n) => n["@type"]);
    for (const required of REQUIRED_TYPES) {
      if (!types.includes(required)) fail(`${p.href}: JSON-LD is missing a ${required} node`);
    }

    const faq = p.graph["@graph"].find((n) => n["@type"] === "FAQPage");
    if (faq) {
      const visible = (p.html.match(/<details class="faq-item">/g) || []).length;
      if (visible !== faq.mainEntity.length) {
        fail(
          `${p.href}: FAQPage has ${faq.mainEntity.length} entries but ${visible} are visible — structured data must match visible content`,
        );
      }
      for (const q of faq.mainEntity) {
        if (!q.name || !q.acceptedAnswer?.text) {
          fail(`${p.href}: FAQPage entry missing a question or answer`);
        }
      }
    }
  }
}

/* ── Internal linking ──────────────────────────────────────────────────── */

const knownHrefs = new Set(pages.map((p) => p.href));
knownHrefs.add("/");

for (const p of pages) {
  const links = [...p.html.matchAll(/<a[^>]+href="([^"]+)"/g)].map((m) => m[1]);

  for (const href of links) {
    if (href.startsWith("http") || href.startsWith("mailto:")) continue;
    if (href.startsWith("#") || href === "/") continue;

    const path = href.split("#")[0].replace(/\/$/, "") || "/";
    if (!knownHrefs.has(path)) {
      // A handful of legitimate non-page targets exist.
      if (/\.(xml|txt|ico|png|svg|webmanifest|json)$/.test(path)) continue;
      fail(`${p.href}: links to "${href}", which is not a generated page or known static file`);
    }
  }
}

// An orphan page can rank but will not be crawled or weighted properly.
for (const p of pages) {
  const inbound = pages.filter(
    (other) =>
      other.href !== p.href &&
      [...other.html.matchAll(/<a[^>]+href="([^"]+)"/g)].some((m) => {
        const href = m[1];
        if (href.startsWith("http") || href.startsWith("#")) return false;
        return (href.split("#")[0].replace(/\/$/, "") || "/") === p.href;
      }),
  );
  if (inbound.length === 0) {
    fail(`${p.href}: orphan page — no other generated page links to it`);
  }
}

/* ── Agreement with the rest of the site ───────────────────────────────── */

async function versionIn(file) {
  try {
    return (await readFile(join(ROOT, file), "utf8")).match(/APP_VERSION\s*=\s*"([^"]+)"/)?.[1];
  } catch {
    return undefined;
  }
}

const appVersion = await versionIn("src/lib/site.ts");
if (!appVersion) {
  fail("src/lib/site.ts: could not read APP_VERSION");
} else {
  const mismatched = pages.filter(
    (p) => p.graph?.["@graph"].find((n) => n["@type"] === "SoftwareApplication")?.softwareVersion !== appVersion,
  );
  for (const p of mismatched) {
    const v = p.graph?.["@graph"].find((n) => n["@type"] === "SoftwareApplication")?.softwareVersion;
    fail(`${p.href}: JSON-LD softwareVersion is "${v}" but src/lib/site.ts has "${appVersion}"`);
  }
}

// The telemetry claim is the most load-bearing sentence on the site, because it
// is also the one an answer engine is most likely to quote. Verify the three
// copies still agree after any edit.
// The SPA entry is the repo-root index.html, which Vite copies to the site
// root. public/ has no index.html of its own.
const homepage = await readFile(join(ROOT, "index.html"), "utf8");
const faqsTs = await readFile(join(ROOT, "src/lib/faqs.ts"), "utf8");
const llms = await readFile(join(PUBLIC, "llms.txt"), "utf8");

if (!/uses Vercel Web Analytics/.test(homepage)) {
  warn("index.html: the homepage does not disclose this site's web analytics — see the FAQ answer on telemetry");
}
if (!/uses Vercel Web Analytics/.test(llms)) {
  warn("public/llms.txt: does not disclose this site's web analytics");
}
if (!/no network calls/.test(faqsTs) && !/no telemetry and no analytics/.test(faqsTs)) {
  warn("src/lib/faqs.ts: the telemetry answer may no longer state the app makes no network calls");
}

/* ── sitemap and llms.txt coverage ─────────────────────────────────────── */

const sitemap = await readFile(join(PUBLIC, "sitemap.xml"), "utf8");
for (const p of pages) {
  const loc = p.href === "/" ? `${SITE_ORIGIN}/` : `${SITE_ORIGIN}${p.href}`;
  if (!sitemap.includes(`<loc>${loc}</loc>`)) {
    fail(`sitemap.xml: missing ${loc}`);
  }
}
const sitemapLocs = [...sitemap.matchAll(/<loc>([^<]+)<\/loc>/g)].map((m) => m[1]);
const expectedLocs = new Set([
  `${SITE_ORIGIN}/`,
  ...pages.map((p) => `${SITE_ORIGIN}${p.href}`),
]);
for (const loc of sitemapLocs) {
  if (!expectedLocs.has(loc)) fail(`sitemap.xml: lists ${loc}, which no longer exists`);
}

for (const p of pages) {
  if (p.href === "/") continue;
  if (!llms.includes(`${SITE_ORIGIN}${p.href}`)) {
    fail(`llms.txt: does not mention ${p.href}`);
  }
}

/* ── Report ────────────────────────────────────────────────────────────── */

console.log(`Checked ${pages.length} generated pages.`);
for (const w of warnings) console.warn(`  warning: ${w}`);

if (errors.length) {
  console.error(`\n${errors.length} SEO/GEO problem(s):`);
  for (const e of errors) console.error(`  - ${e}`);
  process.exit(1);
}

console.log("All SEO/GEO checks passed.");