using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;

namespace Worm.Core;

public enum RiskLevel
{
    Regenerable,  // Safe cache, temp files, build artifacts
    ReDownload,   // Package manager caches; needs a re-download
    UserData,     // Important data, explicit confirmation required
    Unsafe        // Refused by the safety policy
}

/// <summary>
/// How a rule expands into concrete targets. Windows previously had a single
/// implicit shape, which is why it could not express per-child targeting or
/// profile globs.
/// </summary>
public enum RuleKind
{
    /// <summary>The literal directory itself is one target.</summary>
    Directory,

    /// <summary>Every direct child of a base directory is its own target.</summary>
    Children,

    /// <summary>Every matching file (non-recursive) in a directory.</summary>
    Files,

    /// <summary>
    /// Match a pattern whose wildcard sits in the final component, then take
    /// the match itself (depth 0) or its child directories (depth >= 1).
    /// Only the last component may contain * or ?, by design: a recursive
    /// pattern would let a discovery bug reach anywhere.
    /// </summary>
    Glob,

    /// <summary>
    /// Walk one level into every vendor folder under a base directory and take
    /// only the children whose name is a known cache leaf.
    ///
    /// This exists because enumerating the children of %LOCALAPPDATA% or
    /// %APPDATA% wholesale is catastrophic: it targets Packages (every Store and
    /// UWP app's data) and every installed app's own folder. The macOS catalog
    /// does the same thing with its applicationSupportLeaves list, and this is
    /// that approach.
    /// </summary>
    CacheLeaves,
}

public record CleanRule(
    string Id,
    string Name,
    string Category,
    string Description,
    RiskLevel Risk,
    string PathExpression,
    RuleKind Kind = RuleKind.Directory,
    string[]? Extensions = null,
    string[]? KeepNames = null,
    int MinAgeDays = 0,
    int GlobDepth = 0,
    bool RequiresElevation = false
);

/// <summary>
/// The Windows scan catalog.
///
/// Deliberately narrower than a generic "clear temp files" product: every rule
/// targets something that is regenerated by the owning tool. Anything holding
/// real state (toolchain downloads, package caches, credentials) is either
/// absent or surfaced with a re-download badge.
///
/// Known correction from the previous catalog: Gradle targeted
/// %USERPROFILE%\.gradle\caches wholesale, which is broader than intended and
/// swallowed modules-2, a directory the macOS safety policy explicitly hard
/// blocks. It now targets only the task-output cache.
/// </summary>
public static class WindowsScanCatalog
{
    /// <summary>
    /// The only child names CacheLeaves will ever target. Every entry is a
    /// regenerable artefact that Chromium, Electron and .NET rebuild on demand.
    /// Anything not on this list is left alone, which is the entire point: an
    /// installed app's real profile folder is not a cache and must never be
    /// offered for deletion.
    /// </summary>
    public static readonly string[] CacheLeafNames =
    {
        "Cache", "Code Cache", "GPUCache", "DawnCache", "GrShaderCache",
        "GraphiteDawnCache", "DawnGraphiteCache", "DawnWebGPUCache",
        "ShaderCache", "CachedData", "CachedExtensions", "CachedExtensionVSIXs",
        "component_crx_cache", "extensions_crx_cache", "GPUPersistentCache",
        "CacheStorage", "Crashpad", "logs", "log", "Log", "Logs",
        "blob_storage", "Service Worker",
    };

    /// <summary>
    /// Vendor folders that must never be descended into at all. Public because it
    /// documents exactly which folders are safe to walk, and the test suite asserts
    /// against it.
    /// </summary>
    public static readonly string[] NeverDescend =
    {
        "Microsoft", "Packages", "Programs", "Common Files", "Temp", "Windows",
        "System32", "NVIDIA", "AMD", "Intel", "Realtek", "CrashDumps",
        "Application Data", "Desktop", "Start Menu", "Templates", "Recent",
        "SendTo", "NetHood", "Worm", "OneDrive",
    };

    // Shared age gates, named so intent is readable at each call site.
    private const int TempAgeDays = 7;
    private const int LogAgeDays = 7;
    private const int CrashAgeDays = 7;
    private const int StateAgeDays = 30;

    public static IReadOnlyList<string> Categories { get; } = new[]
    {
        "User Essentials",
        "App Caches",
        "Browsers",
        "Cloud & Office",
        "Developer Tools",
        "AI Tools",
        "Apps & Utilities",
        "Virtualization",
        "Logs",
        "System Caches",
        "Misc",
        "Recycle Bin",
        "Old Windows Installations",
    };

    /// <summary>The category selected on launch, mirroring the macOS default.</summary>
    public const string DefaultCategory = "App Caches";

    /// <summary>
    /// Categories that have no scan rules because they are not reachable as a
    /// filesystem path. The Recycle Bin is measured through the Shell API rather
    /// than walked, so it cannot be expressed as a rule and is not subject to the
    /// path-based safety policy. Declared explicitly so the categories list stays
    /// honest and a test can assert the partition rather than assume every
    /// category is rule-backed.
    /// </summary>
    public static bool IsSpecialCategory(string category)
        => category == "Recycle Bin";

    public static IReadOnlyList<string> SpecialCategories { get; }
        = new[] { "Recycle Bin" };

    /// <summary>
    /// Categories that are deliberately excluded from the default selection.
    ///
    /// Old Windows installations are surfaced because they are frequently the
    /// single largest reclaimable item on a machine, but they are not tick-by-
    /// default: rolling back or reinstalling from them is not something to do
    /// by accident. The category is opt-in and every item needs elevation.
    /// </summary>
    public static bool IsOptInCategory(string category)
        => category == "Old Windows Installations";

    public static IReadOnlyList<string> OptInCategories { get; }
        = new[] { "Old Windows Installations" };

    public static IReadOnlyList<CleanRule> GetRules()
    {
        var local = WindowsPaths.LocalAppData;
        var appData = WindowsPaths.AppData;
        var user = WindowsPaths.UserProfile;
        var win = WindowsPaths.WindowsDir;
        var programData = WindowsPaths.ProgramData;

        string L(params string[] parts) => Path.Combine(new[] { local }.Concat(parts).ToArray());
        string A(params string[] parts) => Path.Combine(new[] { appData }.Concat(parts).ToArray());
        string U(params string[] parts) => Path.Combine(new[] { user }.Concat(parts).ToArray());
        string W(params string[] parts) => Path.Combine(new[] { win }.Concat(parts).ToArray());

        var rules = new List<CleanRule>
        {
            // ---------------------------------------------------- User Essentials
            new("user.crashpad", "Application Crash Reports", "User Essentials",
                "Crash dumps written by Chromium and Electron apps", RiskLevel.Regenerable,
                L("CrashDumps"), MinAgeDays: CrashAgeDays),

            new("user.livelock", "LiveLock Error Reports", "User Essentials",
                "LiveApplication SDK error reports", RiskLevel.Regenerable,
                L("LiveKernelReports"), MinAgeDays: CrashAgeDays),

            new("user.dxcache", "DirectX Shader Cache", "User Essentials",
                "Compiled GPU shaders, rebuilt on next launch", RiskLevel.Regenerable,
                L("D3DSCache")),

            // -------------------------------------------------------- App Caches
            // These replaced blanket enumeration of %LOCALAPPDATA% and
            // %APPDATA%, which targeted Packages and every installed app's own
            // folder. Only known cache leaves inside a vendor folder are taken.
            new("app.localcache", "Per-Application Cache", "App Caches",
                "Known cache folders (Cache, Code Cache, GPUCache) inside each app folder",
                RiskLevel.Regenerable, L(), Kind: RuleKind.CacheLeaves),

            new("app.roamingcache", "Roaming Application Cache", "App Caches",
                "Known cache folders inside each roaming app folder", RiskLevel.Regenerable,
                A(), Kind: RuleKind.CacheLeaves),

            new("app.ie.temp", "Internet Explorer Cache", "App Caches",
                "Legacy IE cache files", RiskLevel.Regenerable,
                L("Microsoft", "Windows", "INetCache"), Kind: RuleKind.Files,
                Extensions: new[] { ".tmp", ".dat" }, MinAgeDays: LogAgeDays),

            new("app.explorer.thumb", "Explorer Thumbnail Cache", "App Caches",
                "Cached image and video preview thumbnails", RiskLevel.Regenerable,
                L("Microsoft", "Windows", "Explorer"), Kind: RuleKind.Files,
                Extensions: new[] { ".db" }, KeepNames: new[] { "iconcache" }),

            // --------------------------------------------------------- Browsers
            // Chromium/Electron leaf caches are walked across all profiles rather
            // than hardcoding "Default", which missed every secondary profile.
            new("browser.chromium.cache", "Chromium Profile Caches", "Browsers",
                "Cache folders across every profile", RiskLevel.Regenerable,
                L("Google", "Chrome", "User Data", "*"), Kind: RuleKind.Glob, GlobDepth: 1),

            new("browser.edge.cache", "Edge Profile Caches", "Browsers",
                "Cache folders across every Edge profile", RiskLevel.Regenerable,
                L("Microsoft", "Edge", "User Data", "*"), Kind: RuleKind.Glob, GlobDepth: 1),

            new("browser.brave.cache", "Brave Profile Caches", "Browsers",
                "Cache folders across every Brave profile", RiskLevel.Regenerable,
                L("BraveSoftware", "Brave-Browser", "User Data", "*"), Kind: RuleKind.Glob, GlobDepth: 1),

            new("browser.firefox.cache", "Firefox Profile Caches", "Browsers",
                "cache2 across every Firefox profile", RiskLevel.Regenerable,
                L("Mozilla", "Firefox", "Profiles", "*"), Kind: RuleKind.Glob, GlobDepth: 1),

            new("browser.opera.cache", "Opera Profile Caches", "Browsers",
                "Cache folders across every Opera profile", RiskLevel.Regenerable,
                L("Opera Software", "Opera Stable", "*"), Kind: RuleKind.Glob, GlobDepth: 1),

            new("browser.vivaldi.cache", "Vivaldi Profile Caches", "Browsers",
                "Cache folders across every Vivaldi profile", RiskLevel.Regenerable,
                L("Vivaldi", "*"), Kind: RuleKind.Glob, GlobDepth: 1),

            // ----------------------------------------------------- Cloud & Office
            new("office.onedrive.cache", "OneDrive Cache", "Cloud & Office",
                "Locally cached OneDrive sync state", RiskLevel.Regenerable,
                L("Microsoft", "OneDrive", "logs")),

            new("office.onedrive.setup", "OneDrive Setup Logs", "Cloud & Office",
                "OneDrive installer logs", RiskLevel.Regenerable,
                L("Microsoft", "OneDrive", "setup"), MinAgeDays: LogAgeDays),

            new("office.dropbox.cache", "Dropbox Cache", "Cloud & Office",
                "Locally cached Dropbox thumbnails and sync metadata", RiskLevel.Regenerable,
                L("Dropbox", "cache")),

            new("office.teams.cache", "Teams Cache", "Cloud & Office",
                "Cached Teams media and web content", RiskLevel.Regenerable,
                A("Microsoft", "Teams", "*"), Kind: RuleKind.Glob, GlobDepth: 1),

            // ---------------------------------------------------- Developer Tools
            new("dev.npm.cache", "npm Package Cache", "Developer Tools",
                "Downloaded Node.js tarballs and index records", RiskLevel.ReDownload,
                L("npm-cache")),

            new("dev.npm.logs", "npm Logs", "Developer Tools",
                "npm diagnostic logs", RiskLevel.Regenerable,
                A("npm-cache", "_logs"), MinAgeDays: LogAgeDays),

            new("dev.pnpm.store", "pnpm Store Cache", "Developer Tools",
                "Global pnpm content-addressable store", RiskLevel.ReDownload,
                L("pnpm", "store")),

            new("dev.yarn.cache", "Yarn Cache", "Developer Tools",
                "Yarn package cache", RiskLevel.ReDownload,
                A("Yarn", "Cache")),

            new("dev.nuget.http", "NuGet HTTP Cache", "Developer Tools",
                "Downloaded package archive responses", RiskLevel.ReDownload,
                L("NuGet", "v3-cache")),

            new("dev.pip.cache", "Python pip Cache", "Developer Tools",
                "Downloaded wheels and source distributions", RiskLevel.ReDownload,
                L("pip", "cache")),

            new("dev.cargo.registry", "Cargo Registry Cache", "Developer Tools",
                "Cached crates.io tarballs", RiskLevel.ReDownload,
                U(".cargo", "registry", "cache")),

            // Gradle: only the rebuildable task-output cache. modules-2 and
            // wrapper/dists are toolchain state and hard-blocked by the policy.
            new("dev.gradle.buildcache", "Gradle Task Output Cache", "Developer Tools",
                "Rebuildable Gradle task outputs", RiskLevel.ReDownload,
                U(".gradle", "caches", "build-cache-1")),

            new("dev.gradle.notifications", "Gradle Notifications", "Developer Tools",
                "Gradle desktop notification state", RiskLevel.Regenerable,
                U(".gradle", "notifications")),

            new("dev.gradle.daemon", "Gradle Daemon Logs", "Developer Tools",
                "Gradle daemon logs", RiskLevel.Regenerable,
                U(".gradle", "daemon"), MinAgeDays: LogAgeDays),

            new("dev.vs.component", "Visual Studio Component Cache", "Developer Tools",
                "MEF component catalogues and IntelliSense indices", RiskLevel.Regenerable,
                L("Microsoft", "VisualStudio", "ComponentModelCache")),

            new("dev.vs.crashpad", "Visual Studio Crash Reports", "Developer Tools",
                "Visual Studio crash dumps", RiskLevel.Regenerable,
                A("Microsoft", "VisualStudio", "Crashpad", "reports"), MinAgeDays: CrashAgeDays),

            new("dev.vscode.cache", "VS Code Cached Data", "Developer Tools",
                "VS Code cached extension and workspace data", RiskLevel.Regenerable,
                A("Code", "CachedData")),

            new("dev.vscode.logs", "VS Code Logs", "Developer Tools",
                "VS Code diagnostic logs", RiskLevel.Regenerable,
                A("Code", "logs"), Kind: RuleKind.Files, Extensions: new[] { ".txt", ".log" },
                MinAgeDays: LogAgeDays),

            new("dev.vscode.extensions", "VS Code Extension Cache", "Developer Tools",
                "Downloaded VSIX archives", RiskLevel.ReDownload,
                A("Code", "CachedExtensionVSIXs")),

            new("dev.cursor.cache", "Cursor Cached Data", "Developer Tools",
                "Cursor cached workspace data", RiskLevel.Regenerable,
                A("Cursor", "CachedData")),

            new("dev.jetbrains.cache", "JetBrains Caches", "Developer Tools",
                "JetBrains IDE local caches", RiskLevel.Regenerable,
                L("JetBrains", "*"), Kind: RuleKind.Glob, GlobDepth: 1),

            // Deliberately absent: %USERPROFILE%\.nuget\packages. Restored
            // packages are a dependency source, not rebuildable scratch, and the
            // safety policy hard-blocks it. A rule for it could only ever produce
            // paths the policy refuses, which would look like a broken category.

            new("dev.android.cache", "Android Build Cache", "Developer Tools",
                "Android SDK build and emulator caches", RiskLevel.Regenerable,
                U(".android", "cache")),

            // ---------------------------------------------------------- AI Tools
            new("ai.claude.cache", "Claude Desktop Cache", "AI Tools",
                "Claude Desktop local cache", RiskLevel.Regenerable,
                A("Claude", "Cache")),

            new("ai.codex.logs", "Codex Logs", "AI Tools",
                "Codex agent diagnostic logs", RiskLevel.Regenerable,
                U(".codex", "log"), MinAgeDays: LogAgeDays),

            new("ai.opencode.cache", "OpenCode Cache", "AI Tools",
                "OpenCode local cache", RiskLevel.Regenerable,
                U(".cache", "opencode")),

            new("ai.copilot.cache", "Copilot Cache", "AI Tools",
                "GitHub Copilot local cache", RiskLevel.Regenerable,
                A("GitHub Copilot", "Cache")),

            // --------------------------------------------------- Apps & Utilities
            new("util.discord.cache", "Discord Cache", "Apps & Utilities",
                "Cached Discord media and web content", RiskLevel.Regenerable,
                A("discord", "Cache")),

            new("util.slack.cache", "Slack Cache", "Apps & Utilities",
                "Cached Slack media and web content", RiskLevel.Regenerable,
                A("Slack", "Cache")),

            new("util.teams.browser", "Teams WebView Cache", "Apps & Utilities",
                "Teams embedded browser cache", RiskLevel.Regenerable,
                A("Microsoft", "Teams", "Cache")),

            new("util.spotify.cache", "Spotify Cache", "Apps & Utilities",
                "Cached Spotify audio data", RiskLevel.Regenerable,
                L("Spotify", "Storage")),

            new("util.figma.cache", "Figma Cache", "Apps & Utilities",
                "Cached Figma assets", RiskLevel.Regenerable,
                A("Figma", "Cache")),

            new("util.unity.cache", "Unity Hub Cache", "Apps & Utilities",
                "Unity Hub installer and module cache", RiskLevel.Regenerable,
                A("UnityHub", "Cache")),

            new("util.obsidian.cache", "Obsidian Cache", "Apps & Utilities",
                "Obsidian plugin and workspace cache", RiskLevel.Regenerable,
                A("obsidian", "Cache")),

            new("util.vscode.insiders", "VS Code Insiders Cache", "Apps & Utilities",
                "VS Code Insiders cached data", RiskLevel.Regenerable,
                A("Code - Insiders", "CachedData")),

            new("util.zoom.cache", "Zoom Cache", "Apps & Utilities",
                "Cached Zoom meeting assets", RiskLevel.Regenerable,
                A("Zoom", "Cache")),

            // ----------------------------------------------------- Virtualization
            new("virt.docker.cache", "Docker Desktop Cache", "Virtualization",
                "Docker Desktop builder cache", RiskLevel.Regenerable,
                L("Docker", "*"), Kind: RuleKind.Glob, GlobDepth: 1),

            // Deliberately absent: %LOCALAPPDATA%\Packages\MicrosoftCorporation*
            // WindowsSubsystemForLinux_*. A glob at depth 0 resolves to the whole
            // package folder, which is the distro's filesystem, not a cache.
            // Deleting it would destroy every WSL distribution on the machine.

            new("virt.hyperv.snapshots", "Hyper-V Snapshot Temp", "Virtualization",
                "Temporary Hyper-V checkpoint staging", RiskLevel.Regenerable,
                L("Microsoft", "Hyper-V", "Temp")),

            new("virt.bluestacks.cache", "BlueStacks Cache", "Virtualization",
                "Android emulator cache", RiskLevel.Regenerable,
                L("BlueStacks_nxt", "EngineCache")),

            // ------------------------------------------------------------- Logs
            new("logs.user", "User Log Files", "Logs",
                "Loose log files in your profile", RiskLevel.Regenerable,
                U(), Kind: RuleKind.Files,
                Extensions: new[] { ".log", ".tmp", ".old", ".bak" }, MinAgeDays: LogAgeDays),

            new("logs.appdata", "Application Logs", "Logs",
                "Log folders inside each app folder, never the app folder itself",
                RiskLevel.Regenerable, L(), Kind: RuleKind.CacheLeaves),

            // ---------------------------------------------------- System Caches
            new("sys.temp", "User Temporary Files", "System Caches",
                "Temporary application files and installer leftovers", RiskLevel.Regenerable,
                L("Temp")),

            new("sys.wintemp", "Windows Temporary Files", "System Caches",
                "Temporary files under the Windows directory", RiskLevel.Regenerable,
                W("Temp"), RequiresElevation: true),

            new("sys.wer", "Windows Error Reports", "System Caches",
                "Windows Error Reporting archives", RiskLevel.Regenerable,
                L("Microsoft", "Windows", "WER", "ReportArchive"), MinAgeDays: CrashAgeDays),

            new("sys.deliveryopt", "Delivery Optimization Cache", "System Caches",
                "Peer-to-peer Windows Update distribution cache", RiskLevel.Regenerable,
                W("SoftwareDistribution", "DeliveryOptimization"), RequiresElevation: true),

            new("sys.shader", "Windows Shader Cache", "System Caches",
                "System-wide compiled shader cache", RiskLevel.Regenerable,
                W("Temp", "DXGI")),

            new("sys.prefetch.suggest", "Prefetch Cache", "System Caches",
                "Application prefetch hints, regenerated by Windows", RiskLevel.Regenerable,
                W("Prefetch"), RequiresElevation: true),

            // ------------------------------- Old Windows Installations ------------
            // Reclaimable, but large and consequential. Never ticked by default.
            new("oldwin.oldfolder", "Previous Windows Installation", "Old Windows Installations",
                "A whole earlier copy of Windows you can roll back to. " +
                "Deleting it removes the ability to go back.", RiskLevel.UserData,
                "C:\\Windows.old", MinAgeDays: 30, RequiresElevation: true),

            new("oldwin.upgrader", "Windows Upgrade Files", "Old Windows Installations",
                "Setup files from a feature update. Removing them means you cannot " +
                "roll that update back.", RiskLevel.UserData,
                "C:\\$WINDOWS.~BT", MinAgeDays: 30, RequiresElevation: true),

            new("oldwin.winsxs.backup", "Windows Component Store Backup", "Old Windows Installations",
                "Superstale WinSxS backups from previous updates", RiskLevel.UserData,
                "C:\\Windows.old\\WinSxS", MinAgeDays: 30, RequiresElevation: true),

            new("oldwin.esd", "Windows Installation Image", "Old Windows Installations",
                "ESD/ISO images staged for reinstall", RiskLevel.UserData,
                "C:\\ESD", MinAgeDays: 30, RequiresElevation: true),

            // ------------------------------------------------------------- Misc
            new("misc.minidump", "Minidumps", "Misc",
                "Small crash dumps", RiskLevel.Regenerable,
                L("CrashDumps"), Kind: RuleKind.Files, Extensions: new[] { ".dmp" },
                MinAgeDays: CrashAgeDays),

            new("misc.nuspec.old", "Superseded Installers", "Misc",
                "Old installer packages left by updates", RiskLevel.Regenerable,
                L("Package Cache"), RequiresElevation: true),

            // Crashpad report folders are cache leaves, so they are covered by the
            // CacheLeaves rules above. A dedicated wholesale rule over AppData was
            // removed for the same reason app.localcache was.

            new("misc.dxdiag", "Diagnostic Trace Files", "Misc",
                "Windows diagnostic traces", RiskLevel.Regenerable,
                L("Temp"), Kind: RuleKind.Files, Extensions: new[] { ".etl", ".log" },
                MinAgeDays: TempAgeDays),
        };

        return rules;
    }

    public static IReadOnlyList<CleanRule> RulesFor(string category)
        => GetRules().Where(r => r.Category == category).ToList();

    // ------------------------------------------------------------------ expansion
    /// <summary>
    /// Expand a rule into concrete target paths. Missing paths are skipped, and
    /// every candidate still has to pass the safety policy before it is shown.
    /// </summary>
    public static IEnumerable<string> ExpandTargets(CleanRule rule)
    {
        IEnumerable<string> raw;

        switch (rule.Kind)
        {
            case RuleKind.Directory:
            case RuleKind.Files:
                raw = new[] { WindowsPaths.Expand(rule.PathExpression) };
                break;

            case RuleKind.Children:
                raw = ChildrenOf(WindowsPaths.Expand(rule.PathExpression), rule.KeepNames);
                break;

            case RuleKind.Glob:
                raw = ExpandGlob(rule);
                break;

            case RuleKind.CacheLeaves:
                raw = ExpandCacheLeaves(rule);
                break;

            default:
                raw = Array.Empty<string>();
                break;
        }

        if (rule.Kind == RuleKind.Files)
            raw = raw.Where(p => File.Exists(p) && MatchesExtension(p, rule.Extensions));

        return raw;
    }

    private static IEnumerable<string> ChildrenOf(string basePath, string[]? keepNames)
    {
        if (!Directory.Exists(basePath)) yield break;

        string[] entries;
        try { entries = Directory.GetFileSystemEntries(basePath); }
        catch { yield break; }

        foreach (var entry in entries)
        {
            var name = Path.GetFileName(entry);

            // Never descend into dot-directories.
            if (name.StartsWith('.')) continue;

            if (keepNames != null &&
                keepNames.Any(k => name.Equals(k, StringComparison.OrdinalIgnoreCase)))
            {
                continue;
            }

            yield return entry;
        }
    }

    private static IEnumerable<string> ExpandGlob(CleanRule rule)
    {
        var pattern = WindowsPaths.Expand(rule.PathExpression);
        var dir = Path.GetDirectoryName(pattern);
        var leaf = Path.GetFileName(pattern);

        if (string.IsNullOrEmpty(dir) || string.IsNullOrEmpty(leaf)) yield break;
        if (!Directory.Exists(dir)) yield break;

        if (rule.GlobDepth <= 0)
        {
            foreach (var match in SafeGetDirectories(dir, leaf)) yield return match;
            yield break;
        }

        string[] parents;
        try { parents = SafeGetDirectories(dir, leaf); }
        catch { yield break; }

        foreach (var parent in parents)
        {
            string[] children;
            try { children = Directory.GetDirectories(parent); }
            catch { continue; }
            foreach (var child in children)
            {
                var name = Path.GetFileName(child);
                if (rule.KeepNames != null &&
                    rule.KeepNames.Any(k => name.Equals(k, StringComparison.OrdinalIgnoreCase)))
                {
                    continue;
                }
                yield return child;
            }
        }
    }

    /// <summary>
    /// Two levels deep: every vendor folder under the base, then only its
    /// known cache leaves. A vendor folder itself is never returned.
    /// </summary>
    private static IEnumerable<string> ExpandCacheLeaves(CleanRule rule)
    {
        var baseDir = WindowsPaths.Expand(rule.PathExpression);
        if (!Directory.Exists(baseDir)) yield break;

        string[] vendors;
        try { vendors = Directory.GetDirectories(baseDir); }
        catch { yield break; }

        foreach (var vendor in vendors)
        {
            var vendorName = Path.GetFileName(vendor);
            if (string.IsNullOrWhiteSpace(vendorName)) continue;
            if (vendorName.StartsWith('.')) continue;
            if (NeverDescend.Any(n => n.Equals(vendorName, StringComparison.OrdinalIgnoreCase)))
                continue;

            string[] leaves;
            try { leaves = Directory.GetDirectories(vendor); }
            catch { continue; }

            foreach (var leaf in leaves)
            {
                var leafName = Path.GetFileName(leaf);
                if (!CacheLeafNames.Contains(leafName, StringComparer.OrdinalIgnoreCase)) continue;

                // A leaf that is a junction could point anywhere, so it is only
                // accepted when it resolves inside the vendor folder.
                var resolved = WindowsSafetyPolicy.ResolvePhysicalPath(leaf);
                if (!WindowsSafetyPolicy.IsUnder(resolved, vendor)) continue;

                yield return leaf;
            }
        }
    }

    private static string[] SafeGetDirectories(string dir, string pattern)
    {
        try { return Directory.GetDirectories(dir, pattern); }
        catch { return Array.Empty<string>(); }
    }

    private static bool MatchesExtension(string path, string[]? extensions)
    {
        if (extensions == null || extensions.Length == 0) return true;
        var ext = Path.GetExtension(path);
        // An empty entry in the list means "match everything".
        return extensions.Any(e => e.Length == 0 || e.Equals(ext, StringComparison.OrdinalIgnoreCase));
    }

    /// <summary>Age gate: 0 means always eligible.</summary>
    public static bool PassesAge(string path, int minAgeDays)
    {
        if (minAgeDays <= 0) return true;
        try
        {
            var info = new FileInfo(path);
            if (!info.Exists && !Directory.Exists(path)) return false;
            var stamp = Directory.Exists(path)
                ? Directory.GetLastWriteTime(path)
                : info.LastWriteTime;
            return DateTime.Now - stamp > TimeSpan.FromDays(minAgeDays);
        }
        catch
        {
            return false;
        }
    }

    // -------------------------------------------------------------- allowlist
    /// <summary>
    /// The set of roots a rule is allowed to produce targets inside, derived from
    /// the rules themselves rather than hand-maintained.
    ///
    /// This is the cheapest available bound on the damage a wrong rule can do:
    /// even if discovery produces a surprising path, the safety policy refuses
    /// anything outside these roots. On macOS a hand-kept equivalent list
    /// silently drifted and refused 228 MB of a tool's own cache as "outside a
    /// cleanable folder", so this is derived instead.
    /// </summary>
    public static IEnumerable<string> CleanableRoots()
    {
        var roots = new SortedSet<string>(StringComparer.OrdinalIgnoreCase);

        foreach (var rule in GetRules())
        {
            var expanded = rule.PathExpression;

            switch (rule.Kind)
            {
                case RuleKind.Directory:
                case RuleKind.Children:
                case RuleKind.Files:
                    roots.Add(WindowsPaths.Expand(expanded));
                    break;

                case RuleKind.Glob:
                {
                    // Declare the literal parent of the wildcard, not the pattern.
                    var parent = Path.GetDirectoryName(expanded);
                    if (!string.IsNullOrEmpty(parent)) roots.Add(WindowsPaths.Expand(parent));
                    else roots.Add(WindowsPaths.Expand(expanded));
                    break;
                }
            }
        }

        return roots;
    }
}
